apiVersion: topo.yndd.io/v1alpha1
kind: Template
metadata:
  name: tmpl2
  namespace: tenant1
spec:
  properties:
    fabric:
      maxUplinksTier2ToTier1: 2
      maxUplinksTier3ToTier2: 2
      tier1:
        num: 2
        vendorInfo:
        - vendorType: nokiaSRL
          platform: "IXR-D3"
      pods:
      ## we should not allow mixing explicit pod definitions and references
      - num: 4 # num pods should be ignored if mixing is in use
        tier3:
          num: 4
          uplinkPerNode: 1
          vendorInfo:
          - vendorType: nokiaSRL
            platform: "IXR-D3"
        tier2:
          num: 2
          uplinkPerNode: 1
          vendorInfo:
          - vendorType: nokiaSRL
            platform: "IXR-D3"
      - template-reference: pod-type1 # num pods must be 1, must not have a tier1, must not have another template
      - template-reference: pod-type1 # num pods must be 1, must not have a tier1, must not have another template
      - template-reference: pod-type1 # num pods must be 1, must not have a tier1, must not have another template
      - template-reference: pod-type1 # num pods must be 1, must not have a tier1, must not have another template
      - template-reference: pod-type1 # num pods must be 1, must not have a tier1, must not have another template
      - template-reference: pod-type1 # num pods must be 1, must not have a tier1, must not have another template